"""SPICE netlist generation from circuit netlist data."""
from __future__ import annotations

from wire_detection.core.netlist import Netlist


COMPONENT_NAMES: dict[int, str] = {
    0: "and", 1: "antenna", 2: "capacitor-adjustable", 3: "capacitor-polarized",
    4: "capacitor-unpolarized", 5: "crossover", 6: "crystal", 7: "diac",
    8: "diode", 9: "diode-light_emitting", 10: "diode-thyrector", 11: "diode-zener",
    12: "fuse", 13: "gnd", 14: "inductor", 15: "inductor-ferrite",
    16: "integrated_circuit", 17: "integrated_circuit-ne555",
    18: "integrated_circuit-voltage_regulator", 19: "junction", 20: "lamp",
    21: "magnetic", 22: "mechanical", 23: "microphone", 24: "motor",
    25: "nand", 26: "not", 27: "operational_amplifier", 28: "optocoupler",
    29: "or", 30: "potentiometer", 31: "probe", 32: "relay",
    33: "resistor", 34: "resistor-adjustable", 35: "switch",
    36: "thermistor", 37: "transformer", 38: "transistor",
    39: "transistor-pnp", 40: "triac", 41: "varistor",
    42: "voltage_source", 43: "wire", 44: "terminal",
}

PREFIX_MAP: dict[str, str] = {
    "resistor": "R",
    "resistor-adjustable": "R",
    "capacitor-unpolarized": "C",
    "capacitor-polarized": "C",
    "capacitor-adjustable": "C",
    "inductor": "L",
    "inductor-ferrite": "L",
    "diode": "D",
    "diode-zener": "D",
    "diode-light_emitting": "D",
    "diode-thyrector": "D",
    "diac": "D",
    "voltage_source": "V",
    "transistor": "Q",
    "transistor-pnp": "Q",
    "integrated_circuit": "U",
    "integrated_circuit-ne555": "U",
    "integrated_circuit-voltage_regulator": "U",
    "operational_amplifier": "U",
    "and": "U",
    "nand": "U",
    "or": "U",
    "not": "U",
    "fuse": "F",
    "lamp": "L",
    "switch": "S",
    "relay": "S",
    "motor": "M",
    "crystal": "X",
    "microphone": "U",
    "optocoupler": "U",
    "triac": "T",
    "thermistor": "R",
    "varistor": "R",
    "potentiometer": "R",
    "transformer": "L",
    "crossover": "X",
    "antenna": "E",
    "magnetic": "L",
    "mechanical": "M",
    "junction": "J",
    "terminal": "T",
    "probe": "P",
}

DEFAULT_VALUES: dict[str, str] = {
    "resistor": "1000",
    "resistor-adjustable": "1000",
    "capacitor-unpolarized": "1e-6",
    "capacitor-polarized": "1e-6",
    "capacitor-adjustable": "1e-6",
    "inductor": "1e-3",
    "inductor-ferrite": "1e-3",
    "diode": "D_default",
    "diode-zener": "D_default",
    "diode-light_emitting": "D_default",
    "diode-thyrector": "D_default",
    "diac": "D_default",
    "voltage_source": "DC 5",
    "fuse": "1e-3",
    "lamp": "100",
    "crystal": "1e-6",
    "motor": "1",
    "switch": "1",
    "relay": "1",
    "probe": "1",
    "antenna": "1",
    "magnetic": "1e-3",
    "mechanical": "1",
    "microphone": "1",
    "transformer": "1",
    "potentiometer": "1000",
    "thermistor": "1000",
    "varistor": "1000",
    "crossover": "1",
    "transistor": "100",
    "transistor-pnp": "100",
    "integrated_circuit": "1",
    "integrated_circuit-ne555": "1",
    "integrated_circuit-voltage_regulator": "1",
    "operational_amplifier": "1",
    "and": "1",
    "nand": "1",
    "or": "1",
    "not": "1",
    "optocoupler": "1",
    "triac": "1",
    "junction": "1",
    "terminal": "1",
}


class SpiceGenerator:
    def __init__(self, component_names: dict[int, str] | None = None):
        self._component_names = component_names or COMPONENT_NAMES
        self._prefix_counters: dict[str, int] = {}

    def _get_next_name(self, prefix: str) -> str:
        self._prefix_counters[prefix] = self._prefix_counters.get(prefix, 0) + 1
        return f"{prefix}{self._prefix_counters[prefix]}"

    def _get_prefix(self, type_name: str) -> str | None:
        return PREFIX_MAP.get(type_name)

    def _get_default_value(self, type_name: str) -> str:
        return DEFAULT_VALUES.get(type_name, "1")

    def _get_type_name(self, cls_id: int) -> str:
        return self._component_names.get(cls_id, "resistor")

    def generate(
        self,
        components: list[tuple[int, list[tuple[int, int]], tuple[int, int, int, int]]] | None = None,
        netlist: Netlist | None = None,
    ) -> str:
        if components is None:
            components = []
        if netlist is None:
            netlist = Netlist()

        self._prefix_counters = {}
        lines: list[str] = []
        lines.append("* SPICE netlist generated by Circuit Digitization")

        if not components or not netlist.nodes:
            lines.append(".end")
            return "\n".join(lines)

        gnd_node = self._find_gnd_node(components, netlist)

        node_remap = {}
        if gnd_node is not None:
            node_remap[gnd_node] = "0"

        for node in netlist.nodes:
            nid = node.node_id
            if nid not in node_remap:
                node_remap[nid] = f"N{nid}"

        pin_map = self._build_pin_map(netlist)

        for i, comp in enumerate(components):
            comp_lines = self._generate_component_line(i, comp, pin_map, node_remap)
            if comp_lines:
                lines.extend(comp_lines)

        lines.append(".end")
        return "\n".join(lines)

    def _find_gnd_node(
        self,
        components: list[tuple[int, list[tuple[int, int]], tuple[int, int, int, int]]],
        netlist: Netlist,
    ) -> int | None:
        for i, comp in enumerate(components):
            cls_id = comp[0]
            type_name = self._get_type_name(cls_id)
            if type_name == "gnd":
                for node in netlist.nodes:
                    for pin in node.pins:
                        if pin.component_idx == i:
                            return node.node_id
        return None

    def _build_pin_map(self, netlist: Netlist) -> dict[tuple[int, int], int]:
        pin_map: dict[tuple[int, int], int] = {}
        for node in netlist.nodes:
            for pin in node.pins:
                pin_map[(pin.component_idx, pin.pin_idx)] = node.node_id
        return pin_map

    def _generate_component_line(
        self,
        comp_idx: int,
        comp: tuple[int, list[tuple[int, int]], tuple[int, int, int, int]],
        pin_map: dict[tuple[int, int], int],
        node_remap: dict[int, str],
    ) -> list[str]:
        cls_id = comp[0]
        type_name = self._get_type_name(cls_id)

        if type_name == "gnd":
            return []

        prefix = self._get_prefix(type_name)
        if prefix is None:
            return []

        name = self._get_next_name(prefix)

        pin_nodes = []
        for pin_idx in range(50):
            key = (comp_idx, pin_idx)
            if key in pin_map:
                nid = pin_map[key]
                pin_nodes.append(node_remap.get(nid, f"N{nid}"))
            else:
                break

        if not pin_nodes:
            return []

        value = self._get_default_value(type_name)
        line = f"{name} {' '.join(pin_nodes)} {value}"
        return [line]
